---
title: "Power_Self_Other_Rating"
author: "Annika Frach"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(lme4)
library(lme4)
library(simr)
```


##Participant level predictors
```{r cars}
set.seed(123)

n_participants <- 100
n_addictions <- 10

# Level-2 predictors: HEXACO and PID-5 raw scores (Ashton et al., 2012)
personality <- data.frame(
  target_id = 1:n_participants,
  HEXACO1 = rnorm(n_participants, 3.20, .65),
  HEXACO2 = rnorm(n_participants, 3.32, .63),
  HEXACO3 = rnorm(n_participants, 3.39, .65),
  HEXACO4 = rnorm(n_participants, 2.96, .57),
  HEXACO5 = rnorm(n_participants, 3.48, .54),
  HEXACO6 = rnorm(n_participants, 3.19, .63),
  PID5_1 = rnorm(n_participants, 1.30, .41),
  PID5_2 = rnorm(n_participants, .80, .44),
  PID5_3 = rnorm(n_participants, .87, .46),
  PID5_4 = rnorm(n_participants, 1.27, .36),
  PID5_5 = rnorm(n_participants, .96, .56)
)

```

## Add addictions
```{r pressure, echo=FALSE}
dat <- personality %>%
  slice(rep(1:n(), each = n_addictions)) %>%
  mutate(addiction = factor(rep(1:n_addictions, times = n_participants)))

```

## Self rating
```{r pressure, echo=FALSE}
mean_self <- 2.58
sd_self <- 0.69
meas_err_sd <- .5 ## to add noise


dat <- dat %>%
  group_by(target_id) %>%
  mutate(
    self_rating = rnorm(n_addictions, mean = mean_self, sd = sd_self)
  ) %>%
  ungroup()
## add noise
dat <- dat %>%
  mutate(self_rating_obs = self_rating + rnorm(nrow(dat), 0, meas_err_sd))

## more noise cause it's a likert scale
dat <- dat %>%
  mutate(self_rating = pmin(pmax(round(self_rating), 1), 5))
```


## Other rating
```{r pressure, echo=FALSE}
## scaling self ratings first
dat <- dat %>%
  mutate(
    self_rating_s = scale(self_rating_obs, center = TRUE, scale = TRUE),
    addiction_n = as.numeric(addiction)
  )


r_so <- 0.20
interaction_effect <- 0.05
resid_inflation <-1.5 #to add noise to data

dat <- dat %>%
  rowwise() %>%
  mutate(
    other_rating = rnorm(
      1,
      mean = 2.28 +                        # baseline mean
             r_so * (self_rating - mean_self) +  # self-other correlation
             interaction_effect * (self_rating * as.numeric(addiction)), # interaction
      sd = sqrt((1 - r_so^2) * sd_self^2) *resid_inflation
    )
  ) %>%
  ungroup()



##more noise cause it's on a likert scale
dat <- dat %>%
  mutate(other_rating = pmin(pmax(round(other_rating), 1), 5))



```


## Correlation Self-other rating
```{r pressure, echo=FALSE}
# 
# mean_other <- 2.28
# sd_other <- 0.88
# 
# dat <- dat %>%
#   group_by(target_id) %>%
#   mutate(
#     other_rating = rnorm(n_addictions, mean = mean_other, sd = sd_other)
#   ) %>%
#   ungroup()
# 
# 
# 
# r_so <- 0.38  # self-other correlation (Horwood et al., 2020)
# 
# dat <- dat %>%
#   rowwise() %>%
#   mutate(
#     other_rating = rnorm(1,
#                          mean = 2.58 + r_so*(self_rating - mean_self),
#                          sd = sqrt((1 - r_so^2) * sd_self^2))
#   ) %>%
#   ungroup()
# 
# interaction_effect <- 0.2  # example weight
# dat <- dat %>%
#   rowwise() %>%
#   mutate(
#     other_rating = rnorm(1,
#                          mean = 2.58 +
#                                 r_so*(self_rating - mean_self) +
#                                 interaction_effect * (self_rating * addiction),
#                          sd = sqrt((1 - r_so^2) * sd_self^2))
#   ) %>%
#   ungroup()
```


## Random intercept and slope

```{r pressure, echo=FALSE}
# Random effects for participants
rand_int <- rnorm(n_participants, 0, sqrt(0.5))   # ICC = 0.5
rand_slope <- rnorm(n_participants, 0, sqrt(0.05)) # small slope variance

dat <- dat %>%
  mutate(
    rand_int = rand_int[target_id],
    rand_slope = rand_slope[target_id],
    other_rating = other_rating + rand_int + rand_slope * self_rating
  )
```

### personality effect
```{r pressure, echo=FALSE}
# Relationship strength between addiction and personality
r_values <- c(0.15, 0.20, 0.30)
datasets <- list()

for (r_p in r_values) {
  dat_temp <- dat %>%
    mutate(
      other_rating_adj = other_rating +
        r_p * HEXACO1 +
        r_p * HEXACO2 +
        r_p * HEXACO3 +
        r_p * HEXACO4 +
        r_p * HEXACO5 +
        r_p * HEXACO6 +
        r_p * PID5_1 +
        r_p * PID5_2 +
        r_p * PID5_3 +
        r_p * PID5_4 +
        r_p * PID5_5  # simplified example; can add more HEXACO/PID5
    )
  datasets[[paste0("r_", r_p)]] <- dat_temp
}
```
## Fit Your Multilevel Model\

Use other_rating (not other_rating_adj) for testing interaction power.

For personality effects, use other_rating_adj.
```{r pressure, echo=FALSE}
model1 <- lmer(
  other_rating ~ self_rating * addiction +
    HEXACO1 + HEXACO2 + HEXACO3 + HEXACO4 + HEXACO5 + HEXACO6 +
    PID5_1 + PID5_2 + PID5_3 + PID5_4 + PID5_5 +
    (1 + self_rating | target_id),
  data = datasets$r_0.2,  # example: dataset with r=0.20
   REML = TRUE
)

model2 <- lmer(
  other_rating ~ self_rating * addiction +
    HEXACO1 + HEXACO2 + HEXACO3 + HEXACO4 + HEXACO5 + HEXACO6 +
    PID5_1 + PID5_2 + PID5_3 + PID5_4 + PID5_5 +
    (1 | target_id),
  data = datasets$r_0.2,  # example: dataset with r=0.20
   REML = TRUE
)


model3 <- lmer(
  other_rating ~ self_rating * addiction_n +
    (1 | target_id),
  data = datasets$r_0.2,  # example: dataset with r=0.20
   REML = TRUE
)
summary(model3)



model4 <- lmer(
  other_rating ~ self_rating * addiction +
    HEXACO1 + HEXACO2 + HEXACO3 + HEXACO4 + HEXACO5 + HEXACO6 +
    (1 | target_id),
  data = datasets$r_0.2,  # example: dataset with r=0.20
   REML = TRUE
)

model5 <- lmer(
  other_rating ~ self_rating * addiction_n +
    (1 +self_rating| target_id),
  data = datasets$r_0.2,  # example: dataset with r=0.20
   REML = TRUE
)
summary(model5)


```


```{r pressure, echo=FALSE}

# extend to 300 participants (instead of original 100)
model3_ext <- extend(model3, along="target_id", n=600)
model2_ext <- extend(model2, along="target_id", n=600)
model4_ext <- extend(model4, along="target_id", n=600)
model5_ext <- extend(model5, along="target_id", n=600)


```




```{r pressure, echo=FALSE}
library(simr)

# Define the effect you want to test
ps <- powerSim(model3_ext, fixed("self_rating:addiction_n"), nsim=200)
print(ps)



ps2 <- powerSim(model2_ext, fixed("self_rating:addiction_n"), nsim=200)
print(ps2)

ps4 <- powerSim(model4_ext, fixed("self_rating:addiction_n"), nsim=200)
print(ps4)

ps5 <- powerSim(model5_ext, fixed("self_rating:addiction_n"), nsim=200)
print(ps5)


```



```{r pressure, echo=FALSE}


#simple model
pc <- powerCurve(model3_ext, 
                 fixed("self_rating:addiction_n"), 
                 along="target_id", 
                 nsim=200)
print(pc)
plot(pc)






pc <- powerCurve(model2_ext, 
                 fixed("self_rating:addiction_n"), 
                 along="target_id", 
                 nsim=200)
print(pc)
plot(pc)


pc <- powerCurve(model4_ext, 
                 fixed("self_rating:addiction_n"), 
                 along="target_id", 
                 nsim=200)
print(pc)
plot(pc)


pc <- powerCurve(model3_ext, fixed("self_rating"), along="target_id", nsim=200)
plot(pc)


pc <- powerCurve(model5_ext, 
                 fixed("self_rating:addiction_n"), 
                 along="target_id", 
                 nsim=200)
print(pc)

```